### ISSUE TITLE
Angular Universal with AOT and without AOT Server rendering needed

### ISSUE THREAD

**Issue by imVinayPandya** [Teradata/vantage-ui-template#40] opened 2017-02-16 06:12 UTC
i am new too angular 2, i dont have idea about Angular Universal. i have gone through many articles and universal-cli but i got confused.

### Do you want to request a *feature* or report a *bug*?
feature
#### Feature Request
please make this quick start production ready with Angular Universal, so noob developer like me can easily make production ready app.

**Comment by hardikpatel-1** [comment] 2017-08-10 12:58
I am also facing the same issue and i also have same suggestions

**Comment by emoralesb05** [comment] 2017-08-10 13:55
The problem is that covalent doest not support SSR yet, once this is possible we will update the quickstart.

**Comment by hardikpatel-1** [comment] 2017-08-11 06:36
There is no need for SSR.

Even They can make this quick start production ready Mock(Json) data also.

**Comment by imVinayPandya** [comment] 2017-10-16 07:07
@emoralesb05 any updates SSR??

**Comment by jeremysmartt** [comment] 2020-06-29 20:15
Closing this issue, Covalent support Ivy Rendering

**Closed by jeremysmartt** 2020-06-29 20:15 UTC
Labels: Close Possible
